# Step1: Pipeline ka name
name: RG Pipeline

# Step2: Kab chalega
on:
  push:
    branches:
      - 'feature/*'

# Step3: aapko kya kaam krna hai 
jobs:
  scan:
    # Kaam kis laptop mai hoga 
    runs-on: ubuntu-latest
    
    # Is job ko login ki zaroorat nahi hai agar local files check karni hain
    steps:
      - name: Github Copy kr rha hai code ko aapne computer mai
        uses: actions/checkout@v4
      
      - name: Install Terraform (Setup terraform)
        uses: hashicorp/setup-terraform@v3 
      
      - name: terraform init
        run: terraform init

  plan: 
    name: Manual Approval and Plan
    needs: scan
    runs-on: ubuntu-latest
    environment: production
    
    steps: 
      - name: Github Copy kr rha hai code ko aapne computer mai
        uses: actions/checkout@v4
      
      - name: Install Terraform (Setup terraform)
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login using secret
        uses: azure/login@v3 
        with:
          creds: ${{ secrets.ENV_SET }}
          
          
      - name: terraform init
        run: terraform init

      - name: terraform plan
        run: terraform plan


